quiz/urls.py
from django.urls import path

from .views import (
    QuizView,
    QuizSelectedView,
    DisplayQuestionView,
    ResultView,
)

app_name = 'quiz'

urlpatterns = [
    path('', QuizView.as_view(), name='quiz'),
    path('quiz/<int:pk>/', QuizSelectedView.as_view(), name='quiz_select'),
    path('<int:quiz_id>/<int:question_id>/', DisplayQuestionView.as_view(), name='display_question'),
    path('result/', ResultView.as_view(), name='result'),
]

quiz_service/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('quiz/', include('quiz.urls')),
]

quiz/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

class Quiz(models.Model):
    name = models.CharField(max_length=50)
    desc = models.CharField(max_length=500)
    number_of_questions = models.IntegerField(default=1)
    time = models.IntegerField(help_text="Duration of the quiz in seconds", default="1")

    def __str__(self):
        return self.name

    def get_questions(self):
        return self.question_set.all()


class Question(models.Model):
    content = models.CharField(max_length=200)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)

    def __str__(self):
        return self.content

    def get_answers(self):
        return self.answer_set.all()


def validate_answer(value):
    answers = Answer.objects.filter(question=value)
    correct_answers = answers.filter(correct=True)
    if len(answers) == len(correct_answers):
        raise ValidationError("ERROR")
    else:
        return value

class Answer(models.Model):
    content = models.CharField(max_length=200)
    correct = models.BooleanField(default=False)
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='answer', validators=[validate_answer])

    def __str__(self):
        return f"question: {self.question.content}, answer: {self.content}, correct: {self.correct}"

class Marks_Of_User(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    score = models.FloatField()

    def __str__(self):
        return str(self.user.username)

quiz/forms.py
from django import forms
from .models import (
    Quiz,
    Question,
    Answer,
)

class QuestionForm(forms.ModelForm):

    class Meta:
        model = Question
        fields = "__all__"


class AnswerForm(forms.ModelForm):
    class Meta:
        model  = Answer
        fields = "__all__"

quiz/views.py
from django.shortcuts import get_object_or_404
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from .score import Score

from django.urls import reverse
from .models import (
    Quiz,
    Question,
    Answer,
    User,
    Marks_Of_User,
)


class QuizView(TemplateView):

    template_name = "quiz/quiz.html"
    def get(self, request):
        if request.user.is_anonymous:
            return redirect('account:login')
        quizs = Quiz.objects.all()
        context = {
            'quizs': quizs,
        }
        return render(request, self.template_name, context)


class QuizSelectedView(TemplateView):
    template_name = "quiz/quiz_selected.html"

    def get(self, request, pk):
        quiz = get_object_or_404(Quiz, pk=pk)
        question = quiz.question_set.first()
        return redirect(reverse('quiz:display_question', kwargs={"quiz_id": pk, "question_id": question.pk}))


class DisplayQuestionView(TemplateView):
    template_name = "quiz/display_question.html"

    def get(self, request, quiz_id, question_id):
        quiz = get_object_or_404(Quiz, pk=quiz_id)
        questions = quiz.question_set.all()
        score = Score.get_ScoreforOneAnswer(quiz)
        request.session['puan'] = score
        request.session['score'] = 0
        request.session['quiz_id'] = quiz.id

        answers = []
        current_question, next_question = None, None

        for ind, question, in enumerate(questions):
            if question.pk == question_id:
                answers_q = Answer.objects.filter(question=question)
                correct_answer = Answer.objects.filter(question=questions[ind]).filter(correct=True).values('content')
                for a in answers_q:
                    answers.append(a)
                current_question = question
                if ind != len(questions)-1:
                    next_question = questions[ind + 1]

        return render(self.request,
                      self.template_name,
                      {"quiz": quiz,
                       "question": current_question,
                       "next_question": next_question,
                       "answers": answers,
                       "correct_answer": correct_answer})

    def post(self, request, quiz_id, question_id):
        quiz = get_object_or_404(Quiz, pk=quiz_id)
        questions = quiz.question_set.all()
        b = request.POST
        answers = []
        count_puan = 0
        current_question, next_question = None, None
        corrct_answer, answer = [], []
        for ind, question, in enumerate(questions):
            if question.pk == question_id:
                answers_q = Answer.objects.filter(question=question)
                for a in answers_q:
                    answers.append(a)
                current_question = question
                corrct_answer = Answer.objects.filter(question=questions[ind-1]).filter(correct=True).values('content')
                answer = Answer.objects.filter(question=questions[ind-1]).filter().values('content')
                for i in answer:
                    try:
                        if (str(i['content']) == str(b[i['content']]) and i in corrct_answer):
                            count_puan += 1
                        print(str(i['content']) == str(b[i['content']]) and i in corrct_answer)
                    except:
                        print("ERROR")
                if ind != len(questions) - 1:
                    next_question = questions[ind + 1]
            if count_puan != 0:
                request.session['score'] += count_puan * request.session['puan']
                count_puan = 0
        if next_question is None:
            request.session['last_question'] = questions.last().id
        return render(self.request,
                          self.template_name,
                          {"quiz": quiz,
                           "question": current_question,
                           "next_question": next_question,
                           "answers": answers,
                           "correct_answer": corrct_answer})


class ResultView(TemplateView):
    template_name = 'quiz/result.html'

    def post(self, request):
        quiz = Quiz.objects.get(pk=request.session['quiz_id'])
        last_question_id = request.session['last_question']
        answer = Answer.objects.filter(question_id=last_question_id).\
                                    filter(correct=True).values('content')
        count_score = 0
        b = request.POST
        try:
            for item in answer:
                print(str(item['content']) == str(b[item['content']]))
                if (item['content'] in b[item['content']]):
                    count_score += 1
            request.session['score'] += count_score * request.session['puan']
        except:
            pass
        try:
            score = request.session['score']
            del request.session['score']
            del request.session['puan']
            del request.session['last_question']
            request.session.save()
        except:
            score = 0
        user_mark(request.user, quiz, score)
        return render(request, self.template_name, {'score': score})


def user_mark(user, quiz, score=0):
    return Marks_Of_User.objects.create(user = user, quiz=quiz, score=score)

templates/quiz/change_list.html
{% extends "admin/change_form.html" %}
{% load static %}
{% block content %}
<script src="{% static 'quiz/js/validator.js' %}"></script>
<!-- Render the rest of the ChangeList view by calling block.super -->
{{ block.super }}

{% endblock %}

templates/quiz/display_question.html
{% load static %}
<!DOCTYPE HTML>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Quiz: {{ quiz.name }}</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'quizzes/style.css' %}">
</head>
<body>
    <div class="container">
    <h1>Quiz: {{ quiz.name }}</h1>

    <section class="question">
    {% if question %}
        <fieldset class="form-group">
            <legend>{{ question.prompt }}</legend>

                <br>
                <H1>{{ question.content }}</H1>
                {% if next_question %}
                <form onsubmit="return validateForm(this)"
                      action="{% url 'quiz:display_question' quiz_id=quiz.id question_id=next_question.id %}"
                      method="POST">
                {% csrf_token %}
                    {% for choice in answers %}
            <div class="radio">
            <label>
                <input type="checkbox" class="answers" id="answer" name="{{ choice.content }}" value="{{ choice.content }}">
                {{ choice.content }}
            </label>
            </div>
            {% endfor %}
                 <div style="visibility:hidden; color:red" id="agree_chk_error">
                  At least one mark!
                  </div>
                <div style="visibility:hidden; color:red" id="agree_chk_error2">
                 You can't check all options!
                </div>
                <button type="submit"  class="btn btn-primary">Next</button>
                </form>
            {% else %}
            <form  method="POST"
                   onsubmit="return validateFormResult(this)"
                   action="{% url 'quiz:result' %}">
                {% csrf_token %}
                    {% for choice in answers %}
            <div class="radio">
            <label>
                <input type="checkbox" class="selected_values" name="{{ choice.content }}" value="{{ choice.content }}">
                {{ choice.content }}
            </label>
            </div>
            {% endfor %}
            <div style="visibility:hidden; color:red" id="agree_chk_error">
                  At least one mark!
                  </div>
                <div style="visibility:hidden; color:red" id="agree_chk_error2">
                 You can't check all options!
                </div>
                <div style="margin-top:12px; font-size:16px">
                    <button  onclick="correct_answer()" class="btn btn-primary">See result</button>
                </div>
            </form>
                {% endif %}
            {% endif %}
</body>
<script src="{% static 'quiz/js/validator.js' %}"></script>
</html>

templates/quiz/quiz.html
{% load static %}
<html>
    <head>
        <link rel="stylesheet" href="{% static 'quiz/css/stylesheet.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Test Your Skills</title>
        <link rel="stylesheet" href="{% static 'quiz/css/stylesheet.css' %}">
        <link href="https://fonts.googleapis.com/css?family=Roboto+Slab" rel="stylesheet">
    </head>
    
    <body style="background-image: url('{% static "quiz/img/hero-img.jpg" %}')";>
        <div id="wrapper">
        <nav>
        </nav>
            <div class="Content" >
                {% for quiz in quizs %}
                    <button class="dashboard"><a href="{% url 'quiz:quiz_select' quiz.pk %}">{{ quiz }}</a></button>
                <br>
                <br>
                {% endfor %}

            </div>
        </div>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="{% static 'quiz/js/script.js' %}"></script>
    </body>
</html>

templates/quiz/quiz_selected.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>QUIZ</title>
</head>
<body>
<h1 style="color: red">{{ question.content }}</h1>
 <form method="POST">
 {% csrf_token %}
{% for item in answers %}

    {{ item.content }}<br>

{% endfor %}
<a href="{% url 'quiz:quiz_select' question.pk %}"> <button type="submit">SUBMIT</button></a>
   </form>
</body>
</html>

templates/quiz/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>result</title>
</head>
<body>
<h1>Ваш Балл:{{ score }}</h1>
</body>
</html>